[package]
name = "clf"
version = "0.1.0"
authors = ["Dan DiVica <dandyvica@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
log = "0.4.8"
simplelog = "^0.7.6"
wait-timeout = "0.2.0"
logfile = { version = "^0.1.0", path = "crates/logfile" }
misc = { version = "^0.1.0", path = "crates/misc" }
config = { version = "^0.1.0", path = "crates/config" }

[[bin]]
name = "clf"
path = "src/clf.rs"

[workspace]
members = [
  "crates/logfile",
  "crates/misc",
  "crates/config",
]

# [build.'cfg(windows)']
# target-dir = "c:\temp"

[[test]]
name = "integration"
path = "tests/src/tests.rs"
