[package]
name = "clf"
version = "0.1.0"
authors = ["Dan DiVica <dandyvica@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
flate2 = "1.0.14"
